name: CI_ROS_test

on:
  push:
    branch: [main]


jobs:

# Test for ROS noetic and ROS2
  test:
    build:
      runs-on: ubuntu-latest
      
      steps:
        - name: Check files repository
          uses: actions/checkout@v3

        - name: Setup ROS
          uses: ros-tooling/setup-ros@v0.7
          with:
            required-ros-distributions: noetic
        
        - uses: ros-tooling/action-ros-ci@v0.3
          with:
            import-token: ${{ secrets.GITHUB_TOKEN }}
            target-ros1-distro: noetic
            skip-tests: true

